# Generated by Django 4.2.3 on 2023-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time_min', models.IntegerField()),
                ('time_max', models.IntegerField()),
                ('number_people', models.IntegerField()),
                ('type_recipe', models.CharField(choices=[('regular', 'Regular')], default='regular', max_length=50)),
                ('estimated_price', models.IntegerField()),
                ('total_calories', models.IntegerField()),
            ],
        ),
    ]
