# Generated by Django 4.2.3 on 2023-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_rename_calorie_ingredient_calories'),
        ('recipe', '0004_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_recipe',
            field=models.CharField(choices=[('regular', 'Regular'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snack', 'Snack')], default='regular', max_length=50),
        ),
    ]
