# Generated by Django 4.2.3 on 2023-12-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_recipe_ingredients_alter_recipe_type_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default=recipe.models.get_random_photo_filename, upload_to='photos/'),
        ),
    ]
