# Generated by Django 4.2.3 on 2023-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergen', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calorie', models.FloatField()),
                ('allergens', models.ManyToManyField(to='allergen.allergen')),
                ('tags', models.ManyToManyField(to='tag.tag')),
            ],
        ),
    ]
