# Generated by Django 4.2.3 on 2023-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.CharField(choices=[('L', 'Low'), ('H', 'High')], default='L', max_length=10),
        ),
    ]
