# Generated by Django 4.2.3 on 2023-12-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredient_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='calorie',
            new_name='calories',
        ),
    ]
