# Generated by Django 4.2.3 on 2024-01-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergen', '0001_initial'),
        ('tag', '0001_initial'),
        ('ingredient', '0003_rename_calorie_ingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='allergen.allergen'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.tag'),
        ),
    ]
